# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1373, 755)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("UI_imgs/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("QLabel\n"
"{\n"
"    font: 75 14pt \"微軟正黑體\";\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton\n"
"{\n"
"    font: 75 10pt \"微軟正黑體\";\n"
"    font-weight: bold;\n"
"}\n"
"QScrollBar::horizontal {\n"
"     border: 1px solid #222222;\n"
"     background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0.0 #121212, stop: 0.2 #282828, stop: 1 #484848);\n"
"     height: 10px;\n"
"     margin: 0px 16px 0 16px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal\n"
"{\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0\n"
"      #3282b8, stop: 0.5 #bbe1fa, stop: 1 #3282b8);\n"
"      min-height: 24px;\n"
"      border-radius: 2px;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"      border: 1px solid #1b1b19;\n"
"      border-radius: 2px;\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0\n"
"      #3282b8, stop: 1 #bbe1fa);\n"
"      width: 14px;\n"
"      subcontrol-position: right;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"      border: 1px solid #1b1b19;\n"
"      border-radius: 2px;\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0\n"
"      #3282b8, stop: 1 #bbe1fa);\n"
"      width: 14px;\n"
"     subcontrol-position: left;\n"
"     subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::right-arrow:horizontal, QScrollBar::left-arrow:horizontal\n"
"{\n"
"      border: 1px solid black;\n"
"      width: 1px;\n"
"      height: 1px;\n"
"      background: white;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"      background: none;\n"
"}\n"
"\n"
"QScrollBar:vertical\n"
"{\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0.0 #121212, stop: 0.2 #282828, stop: 1 #484848);\n"
"      width: 10px;\n"
"      margin: 16px 0 16px 0;\n"
"      border: 1px solid #222222;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical\n"
"{\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0\n"
"      #3282b8, stop: 0.5 #bbe1fa, stop: 1 #3282b8);\n"
"      min-height: 24px;\n"
"      border-radius: 2px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical\n"
"{\n"
"      border: 1px solid #1b1b19;\n"
"      border-radius: 2px;\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0\n"
"      #3282b8, stop: 1 #bbe1fa);\n"
"      height: 14px;\n"
"      subcontrol-position: bottom;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical\n"
"{\n"
"      border: 1px solid #1b1b19;\n"
"      border-radius: 2px;\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #bbe1fa,\n"
"      stop: 1 #3282b8);\n"
"      height: 14px;\n"
"      subcontrol-position: top;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical\n"
"{\n"
"      border: 1px solid black;\n"
"      width: 1px;\n"
"      height: 1px;\n"
"      background: white;\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical\n"
"{\n"
"      background: none;\n"
"}")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 10, 491, 236))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.LoginLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.LoginLayout.setContentsMargins(0, 0, 0, 0)
        self.LoginLayout.setObjectName("LoginLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.username = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.username.setObjectName("username")
        self.verticalLayout.addWidget(self.username)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.password = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.verticalLayout.addWidget(self.password)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.login_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.login_btn.setObjectName("login_btn")
        self.verticalLayout_2.addWidget(self.login_btn)
        self.login_and_store_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.login_and_store_btn.setObjectName("login_and_store_btn")
        self.verticalLayout_2.addWidget(self.login_and_store_btn)
        self.auto_login_checkBox = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.auto_login_checkBox.setFont(font)
        self.auto_login_checkBox.setChecked(True)
        self.auto_login_checkBox.setTristate(False)
        self.auto_login_checkBox.setObjectName("auto_login_checkBox")
        self.verticalLayout_2.addWidget(self.auto_login_checkBox)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.LoginLayout.addLayout(self.verticalLayout)
        self.login_status_label = QtWidgets.QLabel(Form)
        self.login_status_label.setGeometry(QtCore.QRect(540, 70, 261, 71))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.login_status_label.setFont(font)
        self.login_status_label.setStyleSheet("QLabel\n"
"{    \n"
"    font: 75 20pt \"微軟正黑體\";\n"
"    font-weight:bold;\n"
"    color: red;\n"
"}")
        self.login_status_label.setObjectName("login_status_label")
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(648, 256, 705, 471))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.am_num_TA_input = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.am_num_TA_input.setFont(font)
        self.am_num_TA_input.setObjectName("am_num_TA_input")
        self.gridLayout.addWidget(self.am_num_TA_input, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.pm_num_TA_input = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pm_num_TA_input.setFont(font)
        self.pm_num_TA_input.setObjectName("pm_num_TA_input")
        self.gridLayout.addWidget(self.pm_num_TA_input, 2, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 3, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.read_demo_time_file_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.read_demo_time_file_btn.setEnabled(False)
        self.read_demo_time_file_btn.setObjectName("read_demo_time_file_btn")
        self.verticalLayout_3.addWidget(self.read_demo_time_file_btn)
        self.set_group_table = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        self.set_group_table.setStyleSheet("QHeaderView::section\n"
"{\n"
"    font: 11pt \"Times New Roman\";\n"
"    font-weight: bold;\n"
"    padding-right:2ex;\n"
"    padding-left:2ex;\n"
"    background-color:#7FB3D2;\n"
"}\n"
"")
        self.set_group_table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.set_group_table.setObjectName("set_group_table")
        self.set_group_table.setColumnCount(3)
        self.set_group_table.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.set_group_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.set_group_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.set_group_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.set_group_table.setHorizontalHeaderItem(2, item)
        self.verticalLayout_3.addWidget(self.set_group_table)
        self.download_hw_from_selection_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.download_hw_from_selection_btn.setEnabled(False)
        self.download_hw_from_selection_btn.setObjectName("download_hw_from_selection_btn")
        self.verticalLayout_3.addWidget(self.download_hw_from_selection_btn)
        self.select_and_unzip_files_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.select_and_unzip_files_btn.setObjectName("select_and_unzip_files_btn")
        self.verticalLayout_3.addWidget(self.select_and_unzip_files_btn)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(8, 256, 625, 469))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.Main_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.Main_layout.setContentsMargins(0, 0, 0, 0)
        self.Main_layout.setObjectName("Main_layout")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.course_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.course_label.sizePolicy().hasHeightForWidth())
        self.course_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.course_label.setFont(font)
        self.course_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.course_label.setObjectName("course_label")
        self.verticalLayout_6.addWidget(self.course_label)
        self.course_selecter = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.course_selecter.sizePolicy().hasHeightForWidth())
        self.course_selecter.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.course_selecter.setFont(font)
        self.course_selecter.setEditable(False)
        self.course_selecter.setObjectName("course_selecter")
        self.verticalLayout_6.addWidget(self.course_selecter)
        self.horizontalLayout_7.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSpacing(4)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.hw_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hw_label.sizePolicy().hasHeightForWidth())
        self.hw_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.hw_label.setFont(font)
        self.hw_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.hw_label.setObjectName("hw_label")
        self.verticalLayout_7.addWidget(self.hw_label)
        self.hw_selecter = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.hw_selecter.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hw_selecter.sizePolicy().hasHeightForWidth())
        self.hw_selecter.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.hw_selecter.setFont(font)
        self.hw_selecter.setObjectName("hw_selecter")
        self.verticalLayout_7.addWidget(self.hw_selecter)
        self.horizontalLayout_7.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.search_files_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.search_files_btn.setEnabled(False)
        self.search_files_btn.setObjectName("search_files_btn")
        self.verticalLayout_8.addWidget(self.search_files_btn)
        self.import_files_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.import_files_btn.setEnabled(False)
        self.import_files_btn.setObjectName("import_files_btn")
        self.verticalLayout_8.addWidget(self.import_files_btn)
        self.horizontalLayout_7.addLayout(self.verticalLayout_8)
        self.Main_layout.addLayout(self.horizontalLayout_7)
        self.num_student_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.num_student_label.setStyleSheet("color:blue")
        self.num_student_label.setObjectName("num_student_label")
        self.Main_layout.addWidget(self.num_student_label)
        self.hw_submitted_status_table = QtWidgets.QTableWidget(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hw_submitted_status_table.sizePolicy().hasHeightForWidth())
        self.hw_submitted_status_table.setSizePolicy(sizePolicy)
        self.hw_submitted_status_table.setObjectName("hw_submitted_status_table")
        self.hw_submitted_status_table.setColumnCount(7)
        self.hw_submitted_status_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.hw_submitted_status_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.hw_submitted_status_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.hw_submitted_status_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.hw_submitted_status_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.hw_submitted_status_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.hw_submitted_status_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.hw_submitted_status_table.setHorizontalHeaderItem(6, item)
        self.Main_layout.addWidget(self.hw_submitted_status_table)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.Main_layout.addWidget(self.label_3)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.sub_hw_selecter_for_delay_selecter = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.sub_hw_selecter_for_delay_selecter.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sub_hw_selecter_for_delay_selecter.sizePolicy().hasHeightForWidth())
        self.sub_hw_selecter_for_delay_selecter.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.sub_hw_selecter_for_delay_selecter.setFont(font)
        self.sub_hw_selecter_for_delay_selecter.setObjectName("sub_hw_selecter_for_delay_selecter")
        self.horizontalLayout_8.addWidget(self.sub_hw_selecter_for_delay_selecter)
        self.delay_time_set = QtWidgets.QDateTimeEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.delay_time_set.setFont(font)
        self.delay_time_set.setStyleSheet("QDateTimeEdit{\n"
"    font: 75 11pt \"微軟正黑體\";\n"
"}")
        self.delay_time_set.setObjectName("delay_time_set")
        self.horizontalLayout_8.addWidget(self.delay_time_set)
        self.set_delay_time = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.set_delay_time.setEnabled(False)
        self.set_delay_time.setObjectName("set_delay_time")
        self.horizontalLayout_8.addWidget(self.set_delay_time)
        self.write_delay_to_setting_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.write_delay_to_setting_btn.setEnabled(False)
        self.write_delay_to_setting_btn.setObjectName("write_delay_to_setting_btn")
        self.horizontalLayout_8.addWidget(self.write_delay_to_setting_btn)
        self.Main_layout.addLayout(self.horizontalLayout_8)
        self.output_submitted_info_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.output_submitted_info_btn.setEnabled(False)
        self.output_submitted_info_btn.setObjectName("output_submitted_info_btn")
        self.Main_layout.addWidget(self.output_submitted_info_btn)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.Main_layout.addItem(spacerItem1)
        self.download_hw_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.download_hw_btn.setEnabled(False)
        self.download_hw_btn.setObjectName("download_hw_btn")
        self.Main_layout.addWidget(self.download_hw_btn)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Homework Downloader"))
        self.label.setText(_translate("Form", "使用者名稱"))
        self.label_2.setText(_translate("Form", "密碼"))
        self.login_btn.setText(_translate("Form", "登入"))
        self.login_and_store_btn.setText(_translate("Form", "儲存密碼並登入"))
        self.auto_login_checkBox.setText(_translate("Form", "每次自動登入"))
        self.login_status_label.setText(_translate("Form", "登入狀態: 未登入"))
        self.am_num_TA_input.setText(_translate("Form", "8"))
        self.label_4.setText(_translate("Form", "上午TA數"))
        self.pm_num_TA_input.setText(_translate("Form", "4"))
        self.label_5.setText(_translate("Form", "下午TA數"))
        self.read_demo_time_file_btn.setText(_translate("Form", "讀取demo時間選擇檔案"))
        item = self.set_group_table.verticalHeaderItem(0)
        item.setText(_translate("Form", "組別全選"))
        item = self.set_group_table.horizontalHeaderItem(0)
        item.setText(_translate("Form", "時段"))
        item = self.set_group_table.horizontalHeaderItem(1)
        item.setText(_translate("Form", "A組"))
        self.download_hw_from_selection_btn.setText(_translate("Form", "根據設定開始下載"))
        self.select_and_unzip_files_btn.setText(_translate("Form", "選擇目錄並解壓縮全部檔案"))
        self.course_label.setText(_translate("Form", "課程"))
        self.hw_label.setText(_translate("Form", "Homework"))
        self.search_files_btn.setText(_translate("Form", "搜尋檔案"))
        self.import_files_btn.setText(_translate("Form", "匯入檔案"))
        self.num_student_label.setText(_translate("Form", "修課人數:"))
        item = self.hw_submitted_status_table.horizontalHeaderItem(0)
        item.setText(_translate("Form", "有效檔案"))
        item = self.hw_submitted_status_table.horizontalHeaderItem(1)
        item.setText(_translate("Form", "無效檔案"))
        item = self.hw_submitted_status_table.horizontalHeaderItem(2)
        item.setText(_translate("Form", "繳交人數"))
        item = self.hw_submitted_status_table.horizontalHeaderItem(3)
        item.setText(_translate("Form", "未繳人數"))
        item = self.hw_submitted_status_table.horizontalHeaderItem(4)
        item.setText(_translate("Form", "遲交人數"))
        item = self.hw_submitted_status_table.horizontalHeaderItem(5)
        item.setText(_translate("Form", "總檔案大小"))
        item = self.hw_submitted_status_table.horizontalHeaderItem(6)
        item.setText(_translate("Form", "遲交時間"))
        self.label_3.setText(_translate("Form", "遲交時間設定:"))
        self.set_delay_time.setText(_translate("Form", "設定"))
        self.write_delay_to_setting_btn.setText(_translate("Form", "寫入設定"))
        self.output_submitted_info_btn.setText(_translate("Form", "匯出繳交資料"))
        self.download_hw_btn.setText(_translate("Form", "全部下載"))
